// 旧路径兼容重定向
export default [
  { path: '/lottery/detail', redirect: '/details' },
  { path: '/lottery/trend-chart', component: () => import('@/views/common/Placeholder.vue'), meta: { title: '走势图' } },
  { path: '/lottery/play-rules', component: () => import('@/views/common/Placeholder.vue'), meta: { title: '玩法规则' } },
  { path: '/lottery/history', redirect: '/results' },
  { path: '/help-detail/:id', component: () => import('@/views/common/Placeholder.vue'), meta: { title: '帮助详情' } },
  { path: '/help-question/:id', component: () => import('@/views/common/Placeholder.vue'), meta: { title: '常见问题' } },
  { path: '/customer-service/:id?', redirect: '/chat' },
  { path: '/activity-detail', redirect: to => ({ path: '/promo', query: to.query }) },
  { path: '/activities', redirect: '/promo' },
  { path: '/recharge', redirect: '/user/recharge' },
  { path: '/withdraw', redirect: '/user/withdraw' },
  { path: '/messages', redirect: '/user/message' },
  { path: '/settings', redirect: '/user/settings' },
  { path: '/bind-phone', redirect: '/user/settings' },
  { path: '/change-login-password', redirect: '/user/settings' },
  { path: '/bank-card-manage', redirect: '/user/bank-cards' },
  { path: '/add-bank-card', redirect: '/user/bank-cards/form' },
  { path: '/add-usdt-address', redirect: '/user/wallet-addresses/form' },
  { path: '/total-account-change', redirect: '/user/account-change-detail' },
  { path: '/vip-level', redirect: '/user/vip' },
  { path: '/direct-recharge', redirect: '/user/recharge' },
  { path: '/balance-treasure', redirect: '/user/yuebao' },
  { path: '/balance-transfer-out', redirect: '/user/transfer' },
  { path: '/balance-transfer-in', redirect: '/user/transfer' },
  { path: '/fund-details', redirect: '/user/transaction' },
  { path: '/profit-records', redirect: '/user/welfare-record' },
  { path: '/promote-earn', redirect: '/user/promote-earn' },
  { path: '/feedback', redirect: '/user/feedback' },
  { path: '/betting-record', redirect: '/user/bet-records' },
  { path: '/betting-result', redirect: '/results' },
  { path: '/betting-detail', redirect: '/details' },
  { path: '/game-record', redirect: '/user/game-records' },
  { path: '/user/game-records', redirect: '/user/game-records' },
  { path: '/access-record', component: () => import('@/views/common/Placeholder.vue'), meta: { title: '访问记录' } },
  { path: '/gift-record', component: () => import('@/views/common/Placeholder.vue'), meta: { title: '礼物记录' } },
  { path: '/red-packet', component: () => import('@/views/common/Placeholder.vue'), meta: { title: '抢红包' } },
  { path: '/red-packet-rules', component: () => import('@/views/common/Placeholder.vue'), meta: { title: '红包规则' } },
  { path: '/games-menu', redirect: '/casino' },
  { path: '/recent-games', component: () => import('@/views/common/Placeholder.vue'), meta: { title: '最近游戏' } },
  { path: '/favorites-games', component: () => import('@/views/common/Placeholder.vue'), meta: { title: '我的收藏' } },
  { path: '/app-download', redirect: '/' },
  { path: '/download-app', redirect: '/' },
  { path: '/claim-records', redirect: '/user/welfare-record' },
  { path: '/loss-rescue', redirect: '/user/loss-rescue' },
  { path: '/commission-claim-records', redirect: '/user/agent-records' }
]
