export default [
  {
    path: '/user',
    name: 'User',
    component: () => import('@/views/user/UserLayout.vue'),
    redirect: '/user/center',
    children: [
      { path: 'center', name: 'UserCenter', component: () => import('@/views/user/Center.vue'), meta: { title: '个人中心' } },
      { path: 'orders', name: 'UserOrders', component: () => import('@/views/user/Orders.vue'), meta: { title: '我的订单', requiresAuth: true, hideTabbar: true } },
      { path: 'recharge', name: 'UserRecharge', component: () => import('@/views/user/Recharge.vue'), meta: { title: '充值', requiresAuth: true, hideTabbar: true } },
      { path: 'payment', name: 'PaymentPage', component: () => import('@/views/user/PaymentPage.vue'), meta: { title: '支付', requiresAuth: true, hideTabbar: true } },
      { path: 'usdt-deposit-order', name: 'UsdtDepositOrder', component: () => import('@/views/user/UsdtDepositOrder.vue'), meta: { title: 'USDT存款订单', requiresAuth: true, hideTabbar: true } },
      { path: 'manual-cny-recharge', name: 'ManualCnyRecharge', component: () => import('@/views/user/ManualCnyRecharge.vue'), meta: { title: '收银台', requiresAuth: true, hideTabbar: true } },
      { path: 'card-secret-redeem', name: 'CardSecretRedeem', component: () => import('@/views/user/CardSecretRedeem.vue'), meta: { title: '充值处理中', requiresAuth: true, hideTabbar: true } },
      { path: 'withdraw', name: 'UserWithdraw', component: () => import('@/views/user/Withdraw.vue'), meta: { title: '提现', requiresAuth: true, hideTabbar: true } },
      { path: 'rebate', name: 'UserRebate', component: () => import('@/views/user/Rebate.vue'), meta: { title: '实时返水', requiresAuth: true, hideTabbar: true } },
      { path: 'rebate/detail', name: 'UserRebateDetail', component: () => import('@/views/user/RebateDetail.vue'), meta: { title: '返水明细', requiresAuth: true, hideTabbar: true } },
      { path: 'rebate/rates', name: 'UserRebateRates', component: () => import('@/views/user/RebateRates.vue'), meta: { title: '返水比例', requiresAuth: true, hideTabbar: true } },
      { path: 'lucky-wheel', name: 'UserLuckyWheel', component: () => import('@/views/user/LuckyWheel.vue'), meta: { title: '幸运转盘', requiresAuth: true, hideTabbar: true } },
      { path: 'bet-reward', name: 'UserBetReward', component: () => import('@/views/user/BetReward.vue'), meta: { title: '投注达标奖励', requiresAuth: true, hideTabbar: true } },
      { path: 'register-bonus', name: 'UserRegisterBonus', component: () => import('@/views/user/RegisterBonus.vue'), meta: { title: '注册赠送彩金', requiresAuth: true, hideTabbar: true } },
      { path: 'bet-records', name: 'BetRecords', component: () => import('@/views/user/BetRecords.vue'), meta: { title: '投注记录', requiresAuth: true, hideTabbar: true } },
      { path: 'transaction', name: 'UserTransaction', component: () => import('@/views/user/Transaction.vue'), meta: { title: '账变记录', requiresAuth: true, hideTabbar: true } },
      { path: 'account-change-detail', name: 'AccountChangeDetail', component: () => import('@/views/user/AccountChangeDetail.vue'), meta: { title: '账变明细', requiresAuth: true, hideTabbar: true } },
      { path: 'deposit-withdraw-record', name: 'DepositWithdrawRecord', component: () => import('@/views/user/DepositWithdrawRecord.vue'), meta: { title: '存取记录', requiresAuth: true, hideTabbar: true } },
      { path: 'share', name: 'UserShare', component: () => import('@/views/user/Share.vue'), meta: { title: '分享赚钱', requiresAuth: true, hideTabbar: true } },
      { path: 'promote-earn', name: 'UserPromoteEarn', component: () => import('@/views/user/PromoteEarn.vue'), meta: { title: '推广赚钱', requiresAuth: true, hideTabbar: true } },
      { path: 'welfare', name: 'UserWelfare', component: () => import('@/views/user/Welfare.vue'), meta: { title: '礼金', requiresAuth: true, hideTabbar: true } },
      { path: 'loss-rescue', name: 'UserLossRescue', component: () => import('@/views/user/LossRescue.vue'), meta: { title: '亏损救援金', requiresAuth: true, hideTabbar: true } },
      { path: 'welfare-record', name: 'WelfareRecord', component: () => import('@/views/user/WelfareRecord.vue'), meta: { title: '礼金记录', requiresAuth: true, hideTabbar: true } },
      { path: 'message', name: 'UserMessage', component: () => import('@/views/user/Message.vue'), meta: { title: '消息', requiresAuth: true, hideTabbar: true } },
      { path: 'announcement', name: 'UserAnnouncement', component: () => import('@/views/user/Announcement.vue'), meta: { title: '系统公告', requiresAuth: true, hideTabbar: true } },
      { path: 'feedback', name: 'UserFeedback', component: () => import('@/views/user/Feedback.vue'), meta: { title: '有奖反馈', requiresAuth: true, hideTabbar: true } },
      { path: 'agent', name: 'UserAgent', component: () => import('@/views/user/Agent.vue'), meta: { title: '代理中心', requiresAuth: true, hideTabbar: true } },
      { path: 'agent-records', name: 'UserAgentRecords', component: () => import('@/views/user/AgentRecords.vue'), meta: { title: '记录详情', requiresAuth: true, hideTabbar: true } },
      { path: 'settings', name: 'UserSettings', component: () => import('@/views/user/Settings.vue'), meta: { title: '设置', requiresAuth: true, hideTabbar: true } },
      { path: 'vip', name: 'UserVip', component: () => import('@/views/user/Vip.vue'), meta: { title: 'VIP特权', requiresAuth: true, hideTabbar: true } },
      { path: 'bank-cards', name: 'UserBankCards', component: () => import('@/views/user/BankCards.vue'), meta: { title: '银行卡管理', requiresAuth: true, hideTabbar: true } },
      { path: 'bank-cards/form', name: 'UserBankCardForm', component: () => import('@/views/user/BankCardForm.vue'), meta: { title: '绑定银行卡', requiresAuth: true, hideTabbar: true } },
      { path: 'wallet-addresses', name: 'UserWalletAddresses', component: () => import('@/views/user/WalletAddresses.vue'), meta: { title: '钱包地址管理', requiresAuth: true, hideTabbar: true } },
      { path: 'wallet-addresses/form', name: 'UserWalletAddressForm', component: () => import('@/views/user/WalletAddressForm.vue'), meta: { title: '绑定钱包地址', requiresAuth: true, hideTabbar: true } },
      { path: 'notification-settings', name: 'UserNotificationSettings', component: () => import('@/views/user/NotificationSettings.vue'), meta: { title: '通知设置', requiresAuth: true, hideTabbar: true } },
      { path: 'device-info', name: 'UserDeviceInfo', component: () => import('@/views/user/DeviceInfo.vue'), meta: { title: '设备信息', requiresAuth: true, hideTabbar: true } },
      { path: 'members', name: 'UserMembers', component: () => import('@/views/user/Members.vue'), meta: { title: '成员详情', requiresAuth: true, hideTabbar: true } },
      { path: 'yuebao', name: 'UserYuebao', component: () => import('@/views/user/Yuebao.vue'), meta: { title: '余额宝', requiresAuth: true, hideTabbar: true } },
      { path: 'transfer', name: 'UserTransfer', component: () => import('@/views/user/Transfer.vue'), meta: { title: '转账', requiresAuth: true, hideTabbar: true } },
      { path: 'profit-loss-report', name: 'UserProfitLossReport', component: () => import('@/views/user/ProfitLossReport.vue'), meta: { title: '盈亏报表', requiresAuth: true, hideTabbar: true } },
      { path: 'game-records', name: 'GameRecords', component: () => import('@/views/user/GameRecords.vue'), meta: { title: '游戏记录', requiresAuth: true, hideTabbar: true } },
      { path: 'switch-record', name: 'SwitchRecord', component: () => import('@/views/user/SwitchRecord.vue'), meta: { title: '转换记录', requiresAuth: true, hideTabbar: true } }
    ]
  }
]
